### ISSUE TITLE
Spy assignment panel: Add option to configure how long tasks are assigned

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#150]
Unsure if this is actually possible, needs additional testing! See #147 for details

**Comment by jmucchiello** [comment]
Or some way to make spy assignments repeat just like trade routes can be set to auto-repeat.

**Comment by astog** [comment]
I might try to make a Better *Espionage* screen mod if time allows for it. Currently my main priority is to add a few lenses people suggested and improve on the performance of [BTS](https://github.com/astog/BTS) (especially late game).

**Comment by chaorace** [comment]
Closed, see #508
