### ISSUE TITLE
Player color makes custom pins hard to distinguish

### ISSUE THREAD

**Issue by mathandcarnage** [CQUI-Org/cqui#154]
Currently all pins are tinted with the inner color of the player's flag. This can sometimes make the pins hard to distinguish between themselves. This is most clearly demonstrated when playing as a civilization like Russia, whose inner color is black.

![20161129203009_1](https://cloud.githubusercontent.com/assets/4811848/20739905/add719d6-b673-11e6-9c62-ae2765ac0500.jpg)

Is it possible to not tint the custom pins while still keeping the color for the default pins?

**Comment by zxcvforz** [comment]
Wasn't the black color a bug? Because it doesn't just happen with Russia, but other civilizations as well. That's why at the moment I'm still just using the un-modded icons and labeling my districts instead. I remember reading about it somewhere that it's got something to do with the game engine loading the civilization colors, but I can't find that thread/issue. Could be at the thread on CivFanatics.com instead.

**Comment by jacks0nX** [comment]
Yeah, I've tried several times to fix this, couldn't get to the root of the issue yet. Drove me crazy. I think one possible reason could be that a default pinm with the original color scheme is created and just afterwards replaced with a custom icon, something seems to not update properly.

**Comment by Auda35** [comment]
I suggest to eliminate the ugly botton used in the default pins, i think it is more clear without it and solves the problem of fhe black colors.
Samples
![civ6screen0013](https://cloud.githubusercontent.com/assets/23282372/20811609/9f171f44-b80e-11e6-9fef-2e6148da0f4a.jpg)
![civ6screen0015](https://cloud.githubusercontent.com/assets/23282372/20811790/48b0839c-b80f-11e6-99b3-97c863a4a0ea.jpg)



Btw, if you dont want to remove it, i remember that i managed to solve the problem of black color just replacing these line (234, 235 in MapPinManager.lua):
  local brighterIconColor :number = DarkenLightenColor(secondaryColor,20,255);
  local darkerIconColor :number = DarkenLightenColor(secondaryColor,-30,255
to
 local brighterIconColor :number = DarkenLightenColor(255,255,255,255,255,255);
 local darkerIconColor	:number = DarkenLightenColor(255,255,255,255,255,255)
It changes the black color with transparent white.
Sample
![civ6screen0017](https://cloud.githubusercontent.com/assets/23282372/20811509/49ce800e-b80e-11e6-9a2e-5b6611e89c7d.jpg)

**Comment by zxcvforz** [comment]
How would you easily edit/delete a pin if there's no button to click? Can we click on the label and reliably open up the pin? Because when a map has 20 or even more pins, it can be dreadful to have to name every single one just so that it's easier to find from a list.

**Comment by jacks0nX** [comment]
@Auda35 in regards to the color bug, have you tried with other civs? What might work for some might not for others. Makes the default pins somewhat hard to see I think, at least for this russia screenshot.

**Comment by Auda35** [comment]
> @Auda35 in regards to the color bug, have you tried with other civs? What might work for some might not for others. Makes the default pins somewhat hard to see I think, at least for this russia screenshot.

Ok, i think i got it. What about this?

![civ6screen0018](https://cloud.githubusercontent.com/assets/23282372/20852734/b607607c-b8e7-11e6-8695-92d25ea3d4f5.jpg)

It works with every civs.
If that is what you want, this is what i did (lines : 

`function MapPinFlag.SetColor( self : MapPinFlag )
  local primaryColor, secondaryColor  = UI.GetPlayerColors( self.m_Player:GetID() );
  local darkerFlagColor :number = DarkenLightenColor(primaryColor,(-85),255);
  local brighterFlagColor :number = DarkenLightenColor(primaryColor,90,255);
  local brighterIconColor :number = DarkenLightenColor(secondaryColor,20,255);
  local darkerIconColor	:number = DarkenLightenColor(secondaryColor,-30,255);
  **local brighterIconColor2 :number = DarkenLightenColor(secondaryColor,255,255);**
  
  local mapPin = self:GetMapPin();
  -- Determine whether the icon is a default map pin icon
  local isDefaultMapPinIcon = string.find(mapPin:GetIconName(), "ICON_MAP_PIN") ~= nil;
          
  -- Only set the color if it's a default map pin icon
  if (isDefaultMapPinIcon) then
    self.m_Instance.UnitIcon:SetColor( brighterIconColor );
  **else self.m_Instance.UnitIcon:SetColor( brighterIconColor2 );**
  end`
