### ISSUE TITLE
Integrate improved tech tree mod

### ISSUE THREAD

**Issue by vttale** [CQUI-Org/cqui#170]
EUI in Civ5 had this great feature where ALL of the things you got from learning a new tech had the icon in the display.  Like, if the tech led to a boost in farm output there was an icon for that.  It'd be really helpful if those existed in Civ6 too.

**Comment by Sesostrismage** [comment]
This mod does that, perhaps it can be incorporated?
https://forums.civfanatics.com/resources/improved-tech-tree.25467/

**Comment by chaorace** [comment]
I've asked the mod author about adding this in the past and have gotten no response. I'll eventually get to clean-room re-implementing this feature, but I still have hopes he will eventually get back to me

**Comment by chaorace** [comment]
Invalidated by latest update
