### ISSUE TITLE
Hide impossible district builds

### ISSUE THREAD

**Issue by vttale** [CQUI-Org/cqui#176]
If I have a city that has no lake or see anywhere within its workable tile range, it will never be able to build a harbour.  Similarly if I have a city with no flat ground that is not otherwise already occupied by a district or wonder, it will never be able to build an aerodrome. 

That said, I like that a city that can't ever build a particular wonder shows that it is still available to be built *somewhere*.  I'd like that to still be visible.   (Hey, speaking of which, is there a list that shows what wonders are in what cities?  I vaguely remember seeing one but now can't find it.)

**Comment by chaorace** [comment]
I'll see about adding this as an option, as for that list thing, I don't think one currently exists

**Comment by chaorace** [comment]
This isn't trivial to implement and has a lot of potential for confusing people. I think I'm going to be axing this idea
