### ISSUE TITLE
Trade route boosts

### ISSUE THREAD

**Issue by vttale** [CQUI-Org/cqui#178]
It's easy to forget what routes might have a boost, particularly if loading up a saved game.  It'd be really nice if the transfer UI indicated where a trader might get a particular advantage.  For example, I've got Great Zimbabwe, so the icon for that next to the city name in the transfer panel would be great.

**Comment by astog** [comment]
That is a great suggestion, and it is relatively easy to program that in.

**Comment by chaorace** [comment]
I'm going to leave this issue up to BTS to implement
