### ISSUE TITLE
Add Unique Unit/District/Building info to loading screen

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#18]
Currently the loading screen provides absolutely no information concerning a civs uniques. The added descriptions shouldn't be long or comprehensive, something like a blurb nabbed from the tech tree tooltip would do the trick

**Comment by RatchetJ** [comment]
I was thinking either like you've stated or maybe list the icons and have the text appear on mouse over, or a mixture of both.

**Comment by chaorace** [comment]
I'm fine with either implementation

**Comment by RatchetJ** [comment]
New patch. I wonder if FrontEnd mods are now viable. Lots of things to take out / change also. How do you think that should be handled?

**Comment by chaorace** [comment]
Ohhhh boy new patch. Time to start comparing filesizes!

**Comment by chaorace** [comment]
@RatchetJ But yeah, if it's fixed I have nothing against putting your change through!

**Comment by RatchetJ** [comment]
No testing for me tonight to see if it's fixed. Too much playing :)

**Comment by chaorace** [comment]
lol I just checked and my last real save dates back to October... Maybe I should just go and enjoy the new patch too

**Comment by chaorace** [comment]
Sacking this proposed change since we still can't modify the loading screen consistently
