### ISSUE TITLE
Missile Silo and Airstrip UI fails to update on save load

### ISSUE THREAD

**Issue by gelodgreat** [CQUI-Org/cqui#201]
Missile Silo and Airstrip not functioning properly. when u restart the game and loaded your save game the airstrip doesnt show how many airslots and missile silo doesnt show missiles. i test this with mod and without mode

**Comment by chaorace** [comment]
I'm going to have to test this, because I'm not sure why this wouldn't be working

**Comment by JHCD** [comment]
I have the same situation...
![error_airstrip](https://cloud.githubusercontent.com/assets/12496340/23205632/e2dfcaa6-f8ea-11e6-86b8-fad8591022f1.jpg)

The problem is, that you couldn't select an airplane...
Airports are working fine.

**Comment by JHCD** [comment]
Note: The error survives, wenn an airplane/silo is destroyed and rebuilded at the same positon.

**Comment by JHCD** [comment]
Nice, I've found my missles... ;)

![silo_wrong](https://cloud.githubusercontent.com/assets/12496340/24043426/c6df2638-0b16-11e7-9679-6d40b9420629.jpg)

**Comment by chaorace** [comment]
Aha! Problem solved then, _closing issue_... (joking)

**Comment by SpaceOgre** [comment]
Does anyone have a save with airports/missile silos I can test with?

**Comment by JHCD** [comment]
Here is a savefile from the game of my last screenshot... visual indication is still broken here (using the actual master branch):

[HARALD HARDRÅDE 3.zip](https://github.com/CQUI-Org/cqui/files/908195/HARALD.HARDRADE.3.zip)
