### ISSUE TITLE
YnAMP maps incompatibility

### ISSUE THREAD

**Issue by Aethyrion** [CQUI-Org/cqui#207]
Nothing happens when selecting district in production tab (only resetting view).

Other activated mods:
- Civ6-YnAMP (current map: Giant Earth)
- MoarUnits_0.42

Seems to be an incompatibility issue with the map, since it works when I remove cqui or when I play a random map.

**Comment by Aethyrion** [comment]
Additionally it is not possible to open the production tab except when the production queue is empty.

**Comment by chaorace** [comment]
Yes, I have no idea why CQUI is so incompatible with Giant Earth, but it definitely is. won-fix for now

**Comment by chaorace** [comment]
New lead concerning this issue from [HandyVac on CivFanatics](https://forums.civfanatics.com/threads/cqui-a-ui-overhaul-now-out-on-steam-workshop.602771/page-29#post-14750719)

**Comment by chaorace** [comment]
That lead ended up being a dead end
