### ISSUE TITLE
Feature Request:  Rebalance Property

### ISSUE THREAD

**Issue by vttale** [CQUI-Org/cqui#227]
Ever founded a new city that isn't working all of its tiles because one of your nearby cities had already expanded to some tiles outside its working radius?  You then have to take a closer look to find out how to assign them.

One thing that would help a lot would be a button that would automatically rebalance tiles that another city can't even work.

I'd say ignore, for now, the mildly complicating issue of future National Parks.  Speaking of which, is it even possible to swap ownership of hexes outside 3?  Is the inability to do so with the default game just a matter of UI or is a core restriction?  I'd dearly love to be able to swap ownership of ANY hex I own, not just those in the working radius.

**Comment by chaorace** [comment]
After further consideration, this steps somewhat outside of the purview of CQUI since it would be automatically doing something for you requiring no prior input or consideration. Closing issue
