### ISSUE TITLE
Move "Our Relationship" info to dedicated panel in diplo menu

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#228]
Currently this info is squeezed into a scrollpanel hidden by a submenu for some reason. There's plenty of available space to move this info to, which I think is a good idea considering how relevant this info often ends up being

See [here](https://www.reddit.com/r/civ/comments/5mqlkl/long_feedback_on_civ6_from_a_longtime_series_fan/) for more info

**Comment by ricanuck** [comment]
If I understand this correctly, it has been solved in #391 and #393.

**Comment by chaorace** [comment]
Ugh wafflebot is still using my account permissions to change labels, what an annoying "feature"
