### ISSUE TITLE
Add action panel blocker for when a city is able to bombard

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#237]
Currently it's very easy to miss out on free damage by ending your turn without bombarding. A change like this would block ending the turn until each bombard-capable city has been acknowledged, similar to how unit movement currently works. Unlike unit movement, a bombard-capable city should stop blocking as long as it has been acknowledged, hopefully preventing situations where a user is "forced" to bombard when they don't want to. This is probably best implemented as an option

**Comment by vttale** [comment]
Similarly, Civ 5 had a notification for each city that could shell an enemy.  These should come back too.

**Comment by SpaceOgre** [comment]
The blocking part is now in place, see #488 and #497
What we are missing atm is to be able to make them block only once, now you have to bombard to end turn. (You can go to cqui settings and turn the feature off to be able to not bombard for the current turn).

**Comment by JHCD** [comment]
You could right-click to end turn, can't you?
