### ISSUE TITLE
Automatically update governor citizen assignments on updates

### ISSUE THREAD

**Issue by bolbass** [CQUI-Org/cqui#247]
Hi,
Is it possible to change max housing to display as a fractional number?  I mean if it is 10.5 I want to see 10.5 and not 10. In that case I know that I need to improve only 1 tile to make it 11 in this city. Or if noone else needs it could you please say how to do so?
Is it possible to automatically reassign citizens and update all other values (housing, production, food, amenities etc.) when open city view or swap/buy tiles?
Please make clicking city icon to center camera on city.

**Comment by chaorace** [comment]
In the future, please keep distinct requests in separate tickets. I understand the desire to not want to spam the ticket system, but it is the correct way to add issues to the tracker. I've created a new issue for the housing request at #248

As for the citizens, I'm pretty sure most of the city governor stuff is handled by gamecore and not something I can touch, this is the same reason we can't update the cultural growth tile after until the turn ends, even if we can't show one this turn because it was bought or otherwise invalidated

As for the city icon, could you describe this more? Clicking the city banner focuses the correct city in every situation I've tested it

**Comment by vttale** [comment]
I think issue #242 is what is meant in the request about the city icon.

**Comment by bolbass** [comment]
Thanks for the reply, and for your work of course.

Yes, seems like I missed that there is already issue #242 where is the same request about the city panel.

In vanilla version it's possible to update citizens and many values the same turn after a tile improvement or swap/buy tiles by clicking the governor button. But there is no this button in the mod so I can't click it manually. That's why I thought that it was possible to add the same part of the code when a user opens city view or swap/buy tiles as if he clicked the governor button.

If it's needed I can edit this issue #247 and leave only automatically reassign citizens request there because there are 2 other requests already created. Should I do it?

**Comment by chaorace** [comment]
@bolbass I can do that

**Comment by chaorace** [comment]
This shouldn't be too difficult overall. There was already a button for this feature in the Vanilla UI, so it's just a matter of figuring out specifically how we'd like to implement it. I think right-clicking the city banner would be a reasonable solution, albeit a little hidden

**Comment by bolbass** [comment]
I think that the best solution here is to make it as a part of a code when left-clicking the city banner and when left-clicking swap/purchase tile buttons.
In that case everytime when a player opens a cityview "the governor" will automatically recalculate changed values (housing, amenities, food, production, etc.) and reassign citizens if it's needed. The same thing when a player clicks swap/purchase tile buttons.
So if it is possible to make it with left-click, all values will always be updated without necessity of extra clicking.

It is already done in vanilla when a player focuses citizens on food or production for example. All values and citizens change automatically.
But when a player clicks swap/purchase tile buttons "the governor" reassigns citizens only and doesn't recalculate values. I think there is just a part of a code missing for these buttons.

**Comment by bolbass** [comment]
I also offer to update the same way all cities data when tile is improved. Now it is updated only for tile city owner (562368fcba1991e6e64fcee78a0bfa1e24a1bb0d). But if we have 2 or more cities with negative amenities and improve luxury resource then we will see data updates only for city owner. So we need to update all cities data on this event to fix it correct. What do you think, @chaorace ?

**Comment by chaorace** [comment]
@bolbass This seems like a pretty harmless edge-case. We also need to be careful with taxing performance, since users are starting to complain about that.

**Comment by bolbass** [comment]
Here is an example. Someone pillages our luxury resource and 4 of our cities become "unhappy" and lose production. So if we don't see these changes on fly we can miss that a wonder won't be finished next turn and get beaten to it.
But I can't say anything about perfomance issues because I haven't seen any troubles on my end. Sure it would be better to update data only for affected cities when swap/improve but I don't know how to identify them.
