### ISSUE TITLE
Show max housing as a fractional number

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#248]
Certain tile improvements increase housing by .5, which is rounded down in the UI. Ideally we could show the true number somewhere

See #247 for more details

**Comment by SpaceOgre** [comment]
Looked into this and the problem is that the City object we get from the CityManager only returns whole numbers. Eg `CityManager.GetCity(0,0):GetGrowth():GetHousingFromImprovements()` shows returns 1 for 2 and 3 farms and then jump to 2 for 4 farms etc.

**Comment by chaorace** [comment]
Welp, closing this since there's nothing we can do about that

**Comment by bolbass** [comment]
I'm still thinking of it :)
I've created a function that counts all improvements like farms, pastures and so on for a city. Then we can multiple this count by 0.5 and we get the real HousingFromImprovements value.  Is there a way to take this value to another function and to another lua file?

**Comment by bolbass** [comment]
This function calculates the real HousingFromImprovements value for selected city.
`function RealHousingFromImprovements()
	
	local pSelectedCity	:table = UI.GetHeadSelectedCity();
	local HousingFromImprovements = 0;
	local tParameters :table = {};

	tParameters[CityCommandTypes.PARAM_MANAGE_CITIZEN] = UI.GetInterfaceModeParameter(CityCommandTypes.PARAM_MANAGE_CITIZEN);

	local tResults :table = CityManager.GetCommandTargets( pSelectedCity, CityCommandTypes.MANAGE, tParameters );
	local tPlots :table = tResults[CityCommandResults.PLOTS];
	
	if tPlots ~= nil and (table.count(tPlots) > 0) then

		for i,plotId in pairs(tPlots) do			

		local kPlot	:table = Map.GetPlotByIndex(plotId);	
		local eImprovementType :number = kPlot:GetImprovementType();

			if( eImprovementType ~= -1 ) then
	
			local kImprovementData = GameInfo.Improvements[eImprovementType].Housing;

				if kImprovementData == 1 then		-- farms, pastures etc.
				HousingFromImprovements = HousingFromImprovements + 1;

				elseif kImprovementData == 2 then	-- stepwells
				HousingFromImprovements = HousingFromImprovements + 2;
	
				end
			end
		end

		TotalHousingFromImprovements = HousingFromImprovements * 0.5;
	end
end`
But I still can't make it to work for any city. Using `for i, pCity in m_pCity:Members() do` I get the result only for the last city.
And I also can't get this value to another lua files and functions. What commands and variables should I use?

**Comment by chaorace** [comment]
Using the event system mostly. You can fire your own luaEvents and catch them from another context. Lua events can carry arguments, which is basically what you're looking for here.

**Comment by bolbass** [comment]
Chris, should I create a branch at CQUI-Org or at my fork next time? And what to do with Report screen commits? Should I pull them here or to @astog directly?

**Comment by chaorace** [comment]
LuaEvents does not need any additional work to use. If you want to fire a new event you just made up, it's as simple as invoking `LuaEvents.CQUI_MyNewEvent( "example", "parameter", 42);` To catch your new event, it's as simple as adding `LuaEvents.CQUI_MyNewEvent.Add( MyHandlerMethod );` to the initialize method in the context you want to be handling the event

As a team member, you are free to either author branches on your own fork, or directly on the CQUI repo. Most contributors seem to prefer authoring branches directly on the CQUI repo, since this reduces complexity somewhat. Branches are deleted upon merging of their respective PRs, if you need one deleted for whatever reason, simply ask me
