### ISSUE TITLE
Quick relations preview

### ISSUE THREAD

**Issue by mp0011** [CQUI-Org/cqui#269]
I like the leaders avatars improvement to show points and stuff.

Can You improve it more by adding relations info? Just to quick view who is in war/alliance/friendly with, without switching to each leader?

Option #1 
Arrows between **hovered** avatar and other leaders. Red for war, light blue for alliance, etc.
in example, Gandhi declared war on Spain. War between Poland and Japan is not visible until I hover Jadwiga or Hojo. 

![image](https://cloud.githubusercontent.com/assets/15564072/22291156/2205e6da-e305-11e6-8be1-a5da07cbd98a.png)

You may also put some additional info above the line, eg. how many turns there are fighting, or which Casus Belli was used. 

Option #2
Another option, maybe simpler, is to change those little relations icons when one of avatars is hovered.
In this case, When Spain is hovered, Gandhi's yellow face should turn to red war icon, and Hojo's into green (if they are friendly). But then, you can't tell who is the invader...

In Civ III, there was simple relations screen, where you could quickly see every war, alliance, defensive pact, trading relations and all other possible relations. I really miss it since then...

**Comment by Sesostrismage** [comment]
Maybe instead of a hover, having a report screen like the global relations from [InfoAddict](http://steamcommunity.com/sharedfiles/filedetails/?id=79000477) in Civ 5?

**Comment by chaorace** [comment]
I am somewhat worried about increasing the complexity of this part of the UI any further. There's already lots of info compressed into that space and I don't really see much merit to having that specific extra chunk of info inserted there. I think having a separate panel for showing this info is going to be the right call, but preferably with some sort of quick-access shortcut for accessing it from the main map ui

**Comment by ricanuck** [comment]
This is I just did, and I think you will all find very cool... I am waiting for chaorace to catch up with the PRs and then add the code that solves this. Basically, when hovering with mouse over any leader icon while holding ALT down, all relation icons will change to reflect relations towards the "mouse-overed" leader. It stays like that until the normal events that update the ribbon, or until the player leader is right-clicked, or until the player leader is "mouse-overed". Super cool.
Relation tooltips are shown for the relation icons only if the selected leader is the player. Also, to make it clear for the player who is selected, the "YouIndicator" (golden corona surrounding the leader icon) envelopes the selected leader.
Cool, isn't it?

Coming soon... it's ready, just don't want to mix it up with the changes already PRd in diplo ribbon.

**Comment by ricanuck** [comment]
BTW, I did not test this with the hanging banner, I am still trying to convince chao to get rid of it and use the extended tooltip (PRd) and now this... come on, Chris...
