### ISSUE TITLE
"Toggle yields ON by default" option not working

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#303]
Hi,

using the Nightly build from 11. Feb 2017 15:59 (newest one) showing resource icons is broken.
After a rollback to the Nightly 03. Feb 2017 04:43 it works again.

I haven't tested any versions between neither of them.
Tested with Civ VI 1.0.0.56

Regards,
Jens

**Comment by chaorace** [comment]
I can't reproduce your issue, here's a picture:

![](http://i.imgur.com/lCy9r1F.png)

How are you installing new versions of CQUI? It's highly unrecommended to just unzip the new files on top of the old files. If you're not already, try deleting the old files first then extracting the new ones

**Comment by JHCD** [comment]
Hi chaorace,
we're not talking about the same icons.
I mean this small icons on each tile: food, gold...

**Comment by chaorace** [comment]
I understand now, you must mean the yield icons.

I just tested and found that the "Toggle yields ON by default" option does indeed not seem to work. I'll look into it for you 👍

**Comment by JHCD** [comment]
Great, it works with the Nightly from 11. Feb... so something was changing wrong...

**Comment by SpaceOgre** [comment]
Not sure why but in the Initialize method in minimappanel.lua `GameConfiguration.GetValue("CQUI_ToggleYieldsOnLoad")` returns nil on start of game but it seems to work like it should when you load a saved game. So it seems that it is accessed to soon?
