### ISSUE TITLE
Implement Lenses: City Range / District Range

### ISSUE THREAD

**Issue by jacks0nX** [CQUI-Org/cqui#31]
This could probably be an idea for yet another lense. What do you think of a lense specifically for city and district ranges. As everybody knows cities have a 3-tile limit, which were conveniently shown in multiple Civ V mods, I kind of always liked that. Could easily be integrated into the settler lense, I already dislike the overloaded one in vanilla though, way too much red for my liking..

Certain districts, or rather buildings within them, have a maximum range, e.g. industry, entertainment etc.
This is not displayed at all and adjusting an already available district-placement lense in regards to that would make it a lot more convenient to plan with I recon.

Any opinions on that?

**Comment by chaorace** [comment]
I think it should be implemented as a new LensLayer

I've just finished investigating how UILenses can be modified and the results are promising! You can't add new enumerations to LensLayers, but you CAN just use arbitrary ints. UILens.ToggleLayerOn will accept anything and it's not just silently rejected either. Then, all you need to do is attach handlers to the Events.LensLayerOn / Events.LensLayerOff events to implement your custom behavior (see OnLensLayerOn function in MinimapPanel.lua for an example handler).

Knowing this, it should be very simple to implement a new LensLayer for district ranges. From the looks of it, SetLayerHexesArea will do the trick. Example: `UILens.SetLayerHexesArea(LensLayers.HEX_COLORING_PLACEMENT, player, unitPlots);` (from WorldInput.lua)

**Comment by jacks0nX** [comment]
Thanks. I'm on it, seems fun.

**Comment by chaorace** [comment]
I've been trying to get lenses to work all day and I've been having no success. Any success on your end?

**Comment by jacks0nX** [comment]
Yeah, not really. The actual lense seems to be activated by UILens.SetActive('WaterAvailability'), which is still a  puzzle to me. It's only used in this one class. So I guess we'd need access or information about the UILens class, maybe?

I guess we could correctly set the layers via UILens.SetLayerHexesColoredArea all day, but without knowing more about SetActive I don't think we'd get much further.

**Comment by chaorace** [comment]
Here's the results of a quick parse of the luas, maybe it will prove useful?

MinimapPanel.lua:171:           UILens.SetActive("Religion");
MinimapPanel.lua:184:           UILens.SetActive("Continent");
MinimapPanel.lua:197:           UILens.SetActive("Appeal");
MinimapPanel.lua:210:           UILens.SetActive("WaterAvailability");
MinimapPanel.lua:223:           UILens.SetActive("Government");
MinimapPanel.lua:236:           UILens.SetActive("OwningCiv");
MinimapPanel.lua:249:           UILens.SetActive("Tourism");
MinimapPanel.lua:365:           UILens.SetActive("Continent");
StrategicView_MapPlacement.lua:81:      UILens.SetActive("DistrictPlacement");  -- turn on all district layers and district
adjacency bonus layers
StrategicView_MapPlacement.lua:293:     UILens.SetActive("DistrictPlacement");  -- turn on all district layers and district
adjacency bonus layers
WorldInput.lua:622:     UILens.SetActive("Default");
WorldInput.lua:641:     UILens.SetActive("Default");
WorldInput.lua:699:             UILens.SetActive("Default");
WorldInput.lua:746:                                     UILens.SetActive(lensNameBase);
WorldInput.lua:825:                             UILens.SetActive(lensNameBase);
WorldInput.lua:902:                                     UILens.SetActive("MovementBad");
WorldInput.lua:1086:    UILens.SetActive("CityManagement");
WorldInput.lua:1092:    UILens.SetActive("Default");
WorldInput.lua:2429:    UILens.SetActive("Default");
WorldInput.lua:2449:    UILens.SetActive("Default");
WorldInput.lua:2455:    UILens.SetActive("Default");
WorldInput.lua:2681:    UILens.SetActive("Default");
WorldInput.lua:2743:            UILens.SetActive("Default");
Choosers\TradeRouteChooser.lua:657:             UILens.SetActive("Default");
Choosers\TradeRouteChooser.lua:673:     UILens.SetActive("TradeRoute");
FrontEnd\LoadScreen.lua:60:             UILens.SetActive("Default");
Panels\UnitPanel.lua:2342:      UILens.SetActive("Default");
Panels\UnitPanel.lua:2450:      UILens.SetActive("Default");
PartialScreens\WorldRankings.lua:1178:          UILens.SetActive("Default");
PartialScreens\WorldRankings.lua:1198:          UILens.SetActive("TourismWithUnits");
WorldView\SelectedUnit.lua:159:                 UILens.SetActive("Default");
WorldView\SelectedUnit.lua:299: UILens.SetActive("Default");
WorldView\SelectedUnit.lua:338: UILens.SetActive("Default");

**Comment by chaorace** [comment]
@jacks0nX It seems this issue has stagnated for now. Would you like to be unassigned for now?

**Comment by jacks0nX** [comment]
Yep, I agree.

**Comment by emperorfool** [comment]
I would love to see a new lens that combined a city and district planner. I use the new map pins to plan districts, but I rarely need to see them so they just end up getting in the way. A lens to let you mark tiles (without using pins, or have them hide with the lens) and see the AoE radius for districts that have buildings with them. Wonders too!

**Comment by astog** [comment]
I can look into that for my mod. I have been looking into the code trying to get the AoE radius. After some string searching in base code I found two things:

```lua
GameInfo.Buildings[buildingHash].RegionalRange   -- Here the building is a district building, ex factory
-- and
pDistrict:GetExtraRegionalRange(); -- The relevant district
```

I don't know how I will display two buildings in a district that have different ranges, but I can display the AoE for district when the mouse hovers above the relevant district. I have being doing something similar for the settler lens, where on mouse hover it shows a border of radius 3, similar to EUI in CIV V

**Comment by chaorace** [comment]
Pretty much fully implemented and not something I'd like to direct further focus toward currently, closing issue
