### ISSUE TITLE
Authors and Special Thanks doesn't fit in UI

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#326]
The description doesn't fit:
![description_cqui](https://cloud.githubusercontent.com/assets/12496340/23296668/72d890ac-fa76-11e6-98fb-79b1e8b3885c.jpg)

Looks better in other Mods... ;)
![description_drub](https://cloud.githubusercontent.com/assets/12496340/23296671/7505c98a-fa76-11e6-833e-76b861378b69.jpg)

**Comment by chaorace** [comment]
You'd think Firaxis would have enabled some kind of reasonable text wrapping...

Anyways, I'll see about manually inserting some line breaks to fix that issue

**Comment by JHCD** [comment]
Where are the attributes for _singleplayer_, _multiplayer_ or _affect savegames_ located?
There is nothing like this in Dales modinfo but there aren't that infos for cqui.

**Comment by chaorace** [comment]
It's configurable in the Modbuddy application. I'd have liked to experiment with that to learn what stores those values, but Modbuddy is currently bugged for lots of people including me, so I can't build any custom packages with it! I'm sure info about that kind of thing is going to start trickling out into the civfanatics forums over the next few days, so expect those flags to get added within the next weekly workshop update or two

**Comment by JHCD** [comment]
Number of Authors doesn't fit too, I had tried it out but I haven't found a way to make a line break.

**Comment by JHCD** [comment]
What the hell... 

Insert line breaks doesn't adjust the left column
![contentui_cqui](https://cloud.githubusercontent.com/assets/12496340/23338750/6a7f5c1c-fc13-11e6-93c4-6ced8f25d952.jpg)

I could commit this... Better as before.

**Comment by chaorace** [comment]
Golden star to Firaxis for UI design on that one... I guess I'll go file a ticket or something and see if we could get a fix for this in three months

**Comment by JHCD** [comment]
@chaorace They will answer, that you have to use one row. ;-)
**Authors** but only one row...
