### ISSUE TITLE
Add method to set defaults that won't be overridden

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#329]
initial position: you have to change the _CQUI_Settings.sql_ during every updated or run the risk of an old file when it has been omitted.

idea: second file where an user could enter his _n_ default settings (subset, flat file?)

implementation: myDefaultSettings overrule _CQUI_Settings.sql_
ignore old or faulty entries.

**Comment by chaorace** [comment]
Perhaps I could add a reference to a non-existant sql file that people can create by copying the existing settings sql? That would enable pretty simple plug n' play without suffering the overriding problem

**Comment by JHCD** [comment]
Yes, something like that!
It must be save, that the local version could be a subset.
For new or changed settings.

**Comment by JHCD** [comment]
Hmmm, the mySettings couldn't be the same thing, because after _cqui_settings.sql_ an **insert** doesn't work anymore... so you have to use **update**-Statements in the _mySettings_-File.

I have implemented that way... works fine, but this will not only be a simple copy that file to another name...

**Comment by JHCD** [comment]
Hmm, work's not as simple as I thought...

Modding.Log:
>[2857940.291] Status: Creating database save point.
[2857940.291] Status: UpdateDatabase - Loading Assets/cqui_databaseschema.sql
[2857940.292] Status: UpdateDatabase - Loading Assets/cqui_settings.sql
[2857940.293] Status: UpdateDatabase - Loading Assets/cqui_settings_update.sql

cqui_settings_update.sql:
>UPDATE CQUI_Settings SET 'Value' = 400 WHERE 'Setting' = 'CQUI_MinimapSize';

I found no error in the logfiles...
Has anybody an idea what goes wrong?

**Comment by chaorace** [comment]
@JHCD I believe the best solution is to define two distinct SQL tables, one derived from default settings file and one derived from the custom settings file. Then in the schema we can merge those two tables with the custom table only overwriting existing values in the default table. This method would allow both files to be identical with omitted or invalid values from the custom table being ignored. The issue is that I'm pretty bad at SQL and it's taking me a while to figure it out!

**Comment by chaorace** [comment]
Here's a stackexchange discussion on a similar topic that may be a good starting point:
http://stackoverflow.com/questions/20358570/overwrite-data-in-one-table-with-data-from-another-if-two-keys-match
