### ISSUE TITLE
Certain conditions can prevent hostile units from highlighting

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#372]
Why are not all units highlighted?

![error_war_unit-highlighting](https://cloud.githubusercontent.com/assets/12496340/23604891/d6bb2b34-025a-11e7-8b21-d11755cb52e0.jpg)

**Comment by chaorace** [comment]
I think this may have something to do with the underlying logic suffering an unhandled exception halfway through. Could you provide the save from this screenshot and perhaps the error log as well?

**Comment by chaorace** [comment]
@JHCD I'm going to need a save file file if I am going to reproduce this issue to properly categorize and address this issue

**Comment by chaorace** [comment]
It's really annoying that wafflebot is still mangling tags. I think I'm going to shut it completely off now
