### ISSUE TITLE
ProductionPanel breaks when the "Civil Engineering" tech is modded out

### ISSUE THREAD

**Issue by Infixo** [CQUI-Org/cqui#387]
There's a line in productionpanel.lua:

if(row.OuterDefenseHitPoints and pPlayer:GetCulture():HasCivic(GameInfo.Civics["CIVIC_CIVIL_ENGINEERING"].Index)) then

It assumes that CIVIC_CIVIL_ENGINEERING is present in DB and this may not always be true. My mod actually removes this Civic and thus Panel breaks. Could you pls add an additional condition, so the line would be:

if(row.OuterDefenseHitPoints and **GameInfo.Civics["CIVIC_CIVIL_ENGINEERING"] ~= nil** and pPlayer:GetCulture():HasCivic(GameInfo.Civics["CIVIC_CIVIL_ENGINEERING"].Index)) then

This fixes the situation.

**Comment by Infixo** [comment]
Hi, there. I've noticed that a new version of CQUI has been posted. 
May I ask why this simple fix has not been included? It's like 1 minute to make this change...

**Comment by chaorace** [comment]
@Infixo 1 programmer, many requests. I promise there's nothing more than a simple lack of time that's prevented this change from getting implemented. I appreciate the gentle nudge and will work towards having this out by the next workshop update for you

**Comment by Infixo** [comment]
Thanks, appreciate it!

**Comment by Infixo** [comment]
Hi, I've checked the files and the update you've made is still going to generate an error. If a civic is missing, then GameInfo.Civics["CIVIC_CIVIL_ENGINEERING"] will return nil. You cannot do .Index at this time. That's why I used ~= nil in my code.

**Comment by chaorace** [comment]
@Infixo Ah, apologies, I'll just lop off the .Index then
