### ISSUE TITLE
Improved Deal Screen mod

### ISSUE THREAD

**Issue by ricanuck** [CQUI-Org/cqui#399]
Hey Chris,
check this out:
http://steamcommunity.com/sharedfiles/filedetails/?id=884220740

I think it is a must for CQUI. Maybe we will need some small modifications, but it's a great addition. Tested and works splendidly. I already asked for permission to incorporate to the owner.

**Comment by chaorace** [comment]
I agree, we should integrate it. Looks like it just hit the workshop, so let's give it a week or two grace period for pushing out any potential bugfix patches so the version we're basing off of is as stable as possible. I figure we could kill two birds with one stone that way: bugfixing and updating

**Comment by ricanuck** [comment]
I will commit it tomorrow after you publish the weekly tonight, so we can start testing it. I did not find anything wrong with it yet in terms of performance, and it looks and works great. There is only on thing we will have to discuss, but it is minor: the mod presents more city info on the side of the other civ than is normally available to the player (as far as I know), and that MAY be considered by hardcore/purists as cheating. SO, if we want to preserve the pure-non-gameplay-altering-UI nature of this mod, we can cut off that part of the code.

I have it already incorporated into my custom CQUI and it works great.

**Comment by JHCD** [comment]
I would prefer this mod without the "cheats"...
But thats something generell... this coloring ressources the other civ has - inclusive gets via dealing - is cheating too.

**Comment by ricanuck** [comment]
@JHCD : the "cheats" will be a debate among users we will have to engage. That's why I wanted to bring the mod into CQUI, so we can tailor it to our "spirit" for CQUI. I.e.: the info about the other civ cities, AFAIK, is not available directly in vanilla, so I would consider that a cheat. The resources info, on the other hand, could be argued to be available if checking CS and suzerains, and map in general. What is being traded, on the other hand, well, I am not sure. We will have to see.

But first we need to try the mod and see if we all like it as a replacement for the present diplomacydealview file. It may be that the present file fulfills CQUI's goals better in the end.

**Comment by chaorace** [comment]
[I believe the debate has already been had](https://www.reddit.com/r/civ/comments/59wca7/cqui_a_civ_vi_ui_mod_reduces_clicks_and_adds_new/d9bxkhg/). I've made a promise to the userbase that CQUI will be a fair-play mod and I don't plan to be breaking it. If something reveals otherwise completely hidden information or enables an advantage _in MP_ (I don't consider the right-click to pass feature an added advantage in MP since passing in any MP game with a turn timer is already quite possible), we don't add it.

**Comment by chaorace** [comment]
Merged as of PR #404

**Comment by JHCD** [comment]
Hi, my feedback to the new Deal Screen:

- Colouring needs getting used to (why not black like the original?)
- Text "my offer" / "your offer" isn't well readable (take normal text)
- Ressources are not ordered similar on both sides
+ Colouring of "duplicates" is better than our red before
+ Suzerain information is nice
- Cheating (city information)

I don't want information to which I normaly have no access to.
There is no possiblity to get the productions city values  in the normal game.

Todos:
1.) Delete this cheating
2.) Some translations are missing (duplicate, untradeable)
3.) Discuss the colouring topic
