### ISSUE TITLE
Kotaku article

### ISSUE THREAD

**Issue by ricanuck** [CQUI-Org/cqui#407]
Not an issue, but a huge praise:

Kotaku published a new article about how much civ 6 has improved in the few months after release, but the article ended being all about the super, wonderful CQUI mod. 

http://kotaku.com/civilization-vi-is-already-so-much-better-1793241642

> **_The mod I really want to talk about, though, is CQUI, which is a complete user interface overhaul. I can’t say this enough: if you only ever get one Civ VI mod, make it this one, because it makes a big difference to how you play, learn about and enjoy the game._**

**Comment by chaorace** [comment]
Oh cool, can't wait to see the traffic stats! Of course, I don't really feel the issue tracker is the best place to be putting this info, but I'll go ahead and leave this issue open for a little while because of how cool a moment this is.

**Comment by JHCD** [comment]
More attention, more issues ;))

**Comment by chaorace** [comment]
You're right... take it all down

**Comment by chaorace** [comment]
Neat! We enjoyed quite the bump in our daily traffic from that article:

![](http://i.imgur.com/8Fq97QT.png)

Good day! Closing "issue" now
