### ISSUE TITLE
Add GPP points p/turn to GP view, top bar as well?

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#41]
GPP points don't appear on the GP view, which is a little silly and an easy QoL improvement. I'm also curious how people feel about the possibility of displaying GPP on the top bar as well. That second feature may be a consideration as a possible advanced option once persistent settings and the dedicated menu become a reality

**Comment by jacks0nX** [comment]
Perhaps it could be displayed similar to the envoy icon, showing a clock as progress only for the GP category that you currently earn points for.

**Comment by chaorace** [comment]
@jacks0nX I like your idea quite a lot! As long as we can show the absolute points per turn in the tooltip I think this is the ideal solution

**Comment by Oscar-IronTower** [comment]
![civ6screen0001](https://cloud.githubusercontent.com/assets/4163757/20642487/d83ea07c-b3ee-11e6-9f3b-5a031ce16d61.jpg)

Current implementation covers part of the rest of the info.

**Comment by chaorace** [comment]
There really isn't enough real-estate in the top panel for displaying GPP/turn and it doesn't seem to be in high demand. Closing this issue
