### ISSUE TITLE
On the diplomacy screen, replace Surprise War if a Casus Belli is available

### ISSUE THREAD

**Issue by brianschamel** [CQUI-Org/cqui#415]
In cases where a Casus Belli is available, I'll almost always want to do that instead of a surprise war.

Additionally, remove the "Casus Belli" tab and add the remaining CBs not shown (and surprise war) to a menu accessible via expando on the new button.

**Comment by ricanuck** [comment]
Persia benefits from Surprise Wars (mobility and reduced WM penalty), so this is not necessarily good, and obviously not general enough of a case.

**Comment by chaorace** [comment]
Closing this issue since surprise wars are not always the objectively inferior option
