### ISSUE TITLE
Oxford University

### ISSUE THREAD

**Issue by plucko00** [CQUI-Org/cqui#416]
Add a message as to which free techs you get from Oxford University.  I don't believe this is shown currently, if it is and I missed it I apologize.

**Comment by JHCD** [comment]
It's randomise when the Oxford University is finished.
As far as I know you can't get the information before.

**Comment by plucko00** [comment]
not before, when it's completed I don't think it tells you what you got.  You have to look at the tech try and figure out what 2 techs you didn't have before that you have now.

**Comment by JHCD** [comment]
You can enable the info in the CQUI config... then you get the original heureka popups

**Comment by plucko00** [comment]
I see, with the pop ups the completed techs will pop up.  Will close this issue.
