### ISSUE TITLE
Restore the assist icons when a builder is selcted

### ISSUE THREAD

**Issue by djtrame** [CQUI-Org/cqui#426]
When the mod is active and you select a Builder, you don't see the icons there to assist you in selecting what you should build.  For instance you'd see a farm icon, a mine icon, a Seaside resort icon, etc.  Those are gone with the mod active.

**Comment by chaorace** [comment]
[In the future, I suggest using the issue search](http://i.imgur.com/iEvmhDf.gifv). You would have seen that this is documented in ticket #134. Just to reassure you: there is currently work being done on this in PR #412
