### ISSUE TITLE
Trading screen broken on Linux

### ISSUE THREAD

**Issue by mlausch1963** [CQUI-Org/cqui#435]
Version info from cqui.modinfo:
Mod id="03B8BDDE-DEAD-BEEF-9540-26E685E3156E" version="0.6"

On **Linux** there's a problem with the trading screen. After clicking "Make Deal" I get the following screen: https://drive.google.com/file/d/0B4NLzt1h6quZV2FyVWc1U2E1MEk/view?usp=sharing 
I verified with the windows version and it looks like the left and right part is missing. 
Also the item screen in empty, but maybe that's and artifact of the display being shifted.
![civ6-trading](https://cloud.githubusercontent.com/assets/8876611/24352860/77840bda-12eb-11e7-8b42-3467cca829c0.jpg)

**Comment by mlausch1963** [comment]
That's the module version
Mod id="03B8BDDE-DEAD-BEEF-9540-26E685E3156E" version="0.6"

**Comment by chaorace** [comment]
Are you using the workshop version, or a nightly from Github? If a nightly, what was the date? Could you also provide the game version you're running? (game version appears on the title screen and pause menu)

**Comment by mlausch1963** [comment]
CQUI is the the workshop version.
The game version is 1.0.0.110(146422), the latest release for Linux.

**Comment by chaorace** [comment]
Ah, this looks like it's caused by a file naming issue, will fix this after merging some pending PRs

**Comment by papaguss** [comment]
I get a similar screen also(pc not linux)
![civ6screen0000](https://cloud.githubusercontent.com/assets/26750241/24508937/0351e986-1533-11e7-9ea4-dc875268fdbb.jpg)

**Comment by alexeyOnGitHub** [comment]
same if I click "make peace" in a diplomacy screen. see the attached screenshot

**Comment by alexeyOnGitHub** [comment]
![image](https://user-images.githubusercontent.com/239741/32008991-9a822f5e-b962-11e7-936c-851989fc49a0.png)

**Comment by alexeyOnGitHub** [comment]
I renamed two "DiplomacyDealView" files (similarly to the commit referenced in this Issue). 
also updated file names inside those xml and lua files to match the new name (lowercased).

```
alexey@alexey-desktop:~/.steam/steam/steamapps/workshop/content/289070/884220740/UI$ ll
total 144
drwxr-xr-x 2 alexey alexey   4096 Oct 25 09:01 ./
drwxr-xr-x 3 alexey alexey   4096 Oct 24 17:31 ../
-rwxr-xr-x 1 alexey alexey 109682 Oct 24 17:31 diplomacydealview.lua*
-rwxr-xr-x 1 alexey alexey  25716 Oct 24 17:31 diplomacydealview.xml*
alexey@alexey-desktop:~/.steam/steam/steamapps/workshop/content/289070/884220740/UI$ pwd
/home/alexey/.steam/steam/steamapps/workshop/content/289070/884220740/UI

```
now I can at least see the trading screen, but it is broken.
see the new screenshot
![image](https://user-images.githubusercontent.com/239741/32009304-9882fdae-b963-11e7-9b19-930f156b3b80.png)

**Comment by alexeyOnGitHub** [comment]
oooooops, looks like I edited "Improved Deal Screen" mod instead of CQUI. apparently, I have them both. 
I wonder if I can remove this broken "deal screen" and continue playing the same saved game... or fix this issue  somehow. :thinking:

**Comment by ProustIdee** [comment]
Hi @alexeyOnGitHub , most of the active development is happening over at https://github.com/Azurency/CQUI_Community-Edition now.

**Comment by alexeyOnGitHub** [comment]
got it, thanks! I added a star to that repo. this mod is just amazing. it makes such a huge difference while playing Civ6!
