### ISSUE TITLE
Text overlays all garbled

### ISSUE THREAD

**Issue by KeeganEad** [CQUI-Org/cqui#436]
This triggered the first time when clicking new production gear for a city.  Only Aztec dlc enabled, no other mods.  

![screen shot 2017-03-27 at 7 24 58 pm](https://cloud.githubusercontent.com/assets/26011894/24382402/083b1c26-1324-11e7-9e82-ecfd28f04069.png)
![screen shot 2017-03-27 at 7 25 02 pm](https://cloud.githubusercontent.com/assets/26011894/24382405/083d5df6-1324-11e7-91be-b013d4b3767b.png)
![screen shot 2017-03-27 at 7 25 15 pm](https://cloud.githubusercontent.com/assets/26011894/24382403/083b5bd2-1324-11e7-9365-78414aecf3ef.png)
![screen shot 2017-03-27 at 7 25 20 pm](https://cloud.githubusercontent.com/assets/26011894/24382406/083edf46-1324-11e7-91a9-878decf943a8.png)
![screen shot 2017-03-27 at 7 25 26 pm](https://cloud.githubusercontent.com/assets/26011894/24382404/083b7ae0-1324-11e7-9dc1-3a890e5159fc.png)

**Comment by chaorace** [comment]
I'm unable to reproduce this issue and I frankly don't think this issue has anything to do with CQUI. Perhaps your graphics drivers automatically updated?

**Comment by ShadowDuke** [comment]
Is not the problem of cqui.
