### ISSUE TITLE
Show fair info in place of old yield value in IDS screen

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#440]
We're removing the old yield value info from non-owned cities, since this info isn't exactly fair to spontaneously know about. That being said, we can still provide useful info in lieu of this, like a list of districts/wonders built, which is generally public knowledge to anyone with enough time to find the city on the map and look carefully

**Comment by ricanuck** [comment]
Districts are already there (as in vanilla). Wonders though... it can be argued that wonders info can only be seen/deducted IF the city is visible. I don't remember what the notification icon says when a wonder is finished: if it states in which city and civ it has been built, EVEN if the city is not yet visible/has not been discovered, then there is no argument as the info is available in vanilla (but you have to take notes).
If that is not the case, then this would be a non-available info. Districts would have the same problem, but they are included in the tooltip in vanilla, so we can not take that out.

**Comment by chaorace** [comment]
Ah, forgot about the tooltips. I seem to remember there being a method for checking if a tile is in the fog of war, which should be exactly what we need to know if a city is visible or not. If we really wanted to get crazy, we could probably individually know which specific districts are/are not in FoW

**Comment by JHCD** [comment]
Keep it simple... use the Civ stuff provided ;)

**Comment by chaorace** [comment]
Brainfart, I meant to type "wonder" instead of "district"

**Comment by JHCD** [comment]
Wonder are overrated at the Deal Screen.
Most of the benefits will stay at the builder anyway.

**Comment by chaorace** [comment]
Fair enough, I guess there's not much to be adding here, then. I'm gonna close this unless someone thinks of something else worth putting there
