### ISSUE TITLE
What happened to the "purchase" icons on city info and production/purchase menu?

### ISSUE THREAD

**Issue by papaguss** [CQUI-Org/cqui#441]
When I have extra $$ I like to purchase units/buildings ect.
I see no icons to do this. Is there a way or has it been omitted from the mod?(The Production Queue is nice)!

**Comment by chaorace** [comment]
[Perhaps you mean these?](http://i.imgur.com/JN5Jze0.png)

If so, those are in the game. If you don't see them, you're likely experiencing a mod conflict and need to resolve that

**Comment by papaguss** [comment]
Thanks,found that  I didn't realize that there were "buy buttons" that could be used.
Whein I didn't see a purchace label on top of the prod. meue ,I was a bit puzzled; untill someone told me about thebuy buttons.
![civ6screen0003](https://cloud.githubusercontent.com/assets/26750241/24467992/b208aee2-1484-11e7-9f6f-6acd00e6df04.jpg)
