### ISSUE TITLE
City Production Panel Crashed

### ISSUE THREAD

**Issue by bentgarden** [CQUI-Org/cqui#446]
I had Rio build the Eiffel Tower, then queued construction of a neighborhood. Production panel won't come up for Rio anymore.
[Production Panel Doesnt Load.zip](https://github.com/CQUI-Org/cqui/files/882185/Production.Panel.Doesnt.Load.zip)
![civvicrash](https://cloud.githubusercontent.com/assets/26792939/24503561/95465bf0-1520-11e7-9dbe-89b22b8ee4a1.jpg)

**Comment by bentgarden** [comment]
I reloaded to an autosave and recreated the problem. Step 1) Build Eiffel Tower (replaces farm immediately left of City Center). Step 2) Build Neighborhood on plains next to Oxford University. The neighborhood doesn't queue, and the production panel will not open anymore on Rio, but it _does_ open on my other cities. If I use the arrows to navigate between cities from the bottom panel, when I get to Rio, it just displays  the info for whatever city I'm clicking away from prior to cycling through to Rio.
[before ETower.zip](https://github.com/CQUI-Org/cqui/files/882281/before.ETower.zip) I'm attaching the save file from immediately before the crash happens.

**Comment by papaguss** [comment]
Same problem .Can't do anything when trying to make a 'DEAL'
 with another player(nothing to choose).either

**Comment by bentgarden** [comment]
I don't think that's a related issue @Papaguss.

**Comment by JHCD** [comment]
I can confirm that topic, here too.

Work-around: in "crashed city production panel" you have to click on another city without leaving it and then you can come back to the original city...

**Comment by papaguss** [comment]
Not it is not a related issue..BUT you should check on this also.

**Comment by ericbond007** [comment]
I have experienced this same bug, though I can't remember what I was building. I don't think it was the Effeil Tower.

I had a number (>6) cities that had queues that crashed. I attempted the workaround suggested by @JHCD with mixed success. After returning to the original city, the build queue is reduced to units only.

**Comment by chaorace** [comment]
I've opened the save and reproduced the issue. Here's a captured stack trace:

Runtime Error: bad argument #2 to 'lLookup' (Argument must be [boolean, number, or string].)
stack traceback:
	[C]: in function 'lLookup'
	C:\Users\chaor\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\Panels\ProductionPanel.lua:1114: in function 'PopulateList'
	C:\Users\chaor\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\Panels\ProductionPanel.lua:482: in function 'View'
	C:\Users\chaor\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\Panels\ProductionPanel.lua:2375: in function 'Refresh'
	[C]: in function 'func'
	[C]: in function '(anonymous)'

**Comment by chaorace** [comment]
I've determined the root cause and am working on a fix now

**Comment by bentgarden** [comment]
Thanks for the quick fix. Can confirm that items are queuing properly again.
