### ISSUE TITLE
Can't clear production queue

### ISSUE THREAD

**Issue by bentgarden** [CQUI-Org/cqui#455]
[cantclearqueue.zip](https://github.com/CQUI-Org/cqui/files/885597/cantclearqueue.zip)
While testing out #454 I noticed this, which also may deal with the production panel, but is probably a different bug - at least I think it's a bug. I cannot totally clear the production menu from all items. The reset button doesn't do anything, but I should note I searched around github and couldn't find any documentation for that button either. If there is only one item in the queue, it can't be removed to leave the queue empty. The work around to this would be to queue something else into production, then remove the thing you want to remove. Again, not sure if it's a bug, but I figure if I want to change my mind on something, I should be able to clear out the queue, do some other stuff, and then come back at the end of the turn to decide what to produce next, instead of having to remember that I wanted to change it.

**Comment by JHCD** [comment]
You can't remove the item in the original game either.
Looks like the same restriction here to.

Have to be analysed if it is possible to do change that behaviour.

**Comment by ricanuck** [comment]
As in vanilla, you remove by changing. In the end, it's what you would do anyways, not that you want to cancel production completely. With the Queue, just add the item that will replace the current production, and then drag and drop it at the top of the queue.
I don't think it's worth the (likely very hacky) code to achieve this.

**Comment by JHCD** [comment]
When we have to change dll files fot it -> _wontfix_

**Comment by bentgarden** [comment]
10-4. I wasn't sure it was a bug or not. It's not. This issue can be closed out if ya'll want.
