### ISSUE TITLE
Check this"make a deal screen"?

### ISSUE THREAD

**Issue by papaguss** [CQUI-Org/cqui#456]
![civ6screen0000](https://cloud.githubusercontent.com/assets/26750241/24554031/31c3283a-15fa-11e7-8be9-7cc567be54e6.jpg)
nothing to choose.To get out of it you have to press'Alt-Tab>close window in the taskba>go back to to the  game screen and choose exit game from the hidden menu that you can barely see.

**Comment by chaorace** [comment]
Please provide an affected save file

**Comment by papaguss** [comment]
Did some troubleshoooting;Ran a Vanillia game mod worked A-OK.Problem was a mod conflict(
Research Tooltips v1.1.).Have tested CQUI with over 20+mods,successfully.
Keep up the good work!!

**Comment by ricanuck** [comment]
Great!
