### ISSUE TITLE
Tile yield icon display issue

### ISSUE THREAD

**Issue by Dralamir** [CQUI-Org/cqui#457]
Any idea what's going on with the yield icons?

![yieldicons](https://cloud.githubusercontent.com/assets/698735/24557158/5d330b76-163f-11e7-8c1b-0e2ab06e70f5.PNG)

**Comment by chaorace** [comment]
[This is literally one of the most reported not-bugs in the entire repo](https://github.com/CQUI-Org/cqui/issues?utf8=%E2%9C%93&q=is%3Aissue%20resource%20is%3Aclosed%20resource%20icon), please use the search function next time

**Comment by Dralamir** [comment]
I did, but apparently with wrong search terms. Sorry.
