### ISSUE TITLE
Middle Mouse Button doesn't register anymore

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#459]
It would seem that it's no longer possible to bind the middle mouse button, this is probably a bug introduced with #418

**Comment by ricanuck** [comment]
told you MM button was a bad idea...

**Comment by ricanuck** [comment]
...mine does...

**Comment by chaorace** [comment]
Let's agree to disagree then.

Hey @JHCD, when you try binding MM, are you able to? What about using MM to recenter camera?

**Comment by ricanuck** [comment]
Oh, OK, now I see what you meant... I thought you meant the MM button does not work to select a different leader for relations view anymore...

**Comment by ricanuck** [comment]
Still, I am not sure it is a bug... let me try some magic.

**Comment by ricanuck** [comment]
I know what it is: remember your recommendation of using return true inside the input handler to stop the clicking of the leader icons from also moving around the map?

Well... you got what you wanted. It stopped the MM from doing what it is supposed to do by default, and also from binding.  :)))))))

You want me to go back to how it was originally?

Then you will have the complaints that when selecting a new leader in diplo ribbon, the map moves around "like crazy"... hehe.

**Comment by chaorace** [comment]
MM not being bindable is minor and fixable, I don't think it's worth throwing out. I know it's not exactly your hill to die on, so I'll be adopting this bug

**Comment by ricanuck** [comment]
kidok... let me know how you fix it.

**Comment by JHCD** [comment]
I don't have a middle mouse button...

**Comment by ricanuck** [comment]
Now that is a really serious bug, the worst I have seen coming from Firaxis... how dare they ship Civ 6 without a middle button for your mouse...?
Let me see if I can fix it. Patience.
