### ISSUE TITLE
Text incomplete in reports view

### ISSUE THREAD

**Issue by gelodgreat** [CQUI-Org/cqui#461]
Text incomplete in reports view
![bug](https://cloud.githubusercontent.com/assets/20021423/24573211/061726a0-16b3-11e7-812a-19182a43b755.png)

**Comment by chaorace** [comment]
[I can't replicate your issue on latest nightly](http://i.imgur.com/EjtKnrw.png), please provide an affected save file

**Comment by gelodgreat** [comment]
@chaorace 
https://drive.google.com/open?id=0B0k2qUZxX80KZmFlejRQRHJrZGM

**Comment by ricanuck** [comment]
Can't replicate.
