### ISSUE TITLE
City Production View will not show

### ISSUE THREAD

**Issue by dimethylman** [CQUI-Org/cqui#462]
Only mods in use are CQUI and More Lenses.  I removed the minimap lua and xml files from CQUI.

After saving and quitting my game last night and then relaunching today, I can no longer open the production menu for any city.  It's my turn and I'm asked to select production, but when I click on the button, it brings me to the city, unit icons disappear as if the menu is up, but it doesn't show the production menu.  I cannot use any keys to select production either.  The city view panel works just fine on the opposite side of the screen.  I've tried reloading older saves, but the problem persists.  

I've uploaded an effected save file.

**Comment by chaorace** [comment]
I dare ask... _where_ did you upload an affect save file?

**Comment by dimethylman** [comment]
Ok I thought I had uploaded it, but apparently I can't upload my zip file.  Any suggestions for the save file?

**Comment by ricanuck** [comment]
@dimethylman : googledrive

**Comment by dimethylman** [comment]
https://drive.google.com/open?id=0B_Yf3FIcN-UnM3N1akgwOGZyRFk

**Comment by chaorace** [comment]
ML is already in CQUI and trying to load it again is known to break CQUI

**Comment by dimethylman** [comment]
Ah so remove the whole ML folder and not just the xml and lua files?

**Comment by chaorace** [comment]
Just delete everything in the ML folder except for the .modinfo file, that should work

**Comment by twdkeule** [comment]
I have the same issue. However I only had Detailed Worlds and ProductionQueue installed.

**Comment by JHCD** [comment]
ProductionQueue is a part of CQUI so you have not to use it at the same time... Could be the problem.

**Comment by chaorace** [comment]
@dimethylman Hasn't responded for 7 days now, closing issue

**Comment by twdkeule** [comment]
Deleting all files in ProductionQueue (except .modinfo) solved the issue fort me. Thanks!
