### ISSUE TITLE
Report Screen: Ressource-Label is missing

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#471]
The label for _bonus_ ressources isn't working...

Report Screen -> Ressources
![rs_ressource_label_missing](https://cloud.githubusercontent.com/assets/12496340/24585827/c5cd40de-1793-11e7-9b5c-c5457201f9fd.jpg)

**Comment by SpaceOgre** [comment]
It works for me:
![image](https://cloud.githubusercontent.com/assets/381657/24588493/acd39c8c-17c9-11e7-8c33-b1b568bc879f.png)

Could it be a that the text is to long in German? Or Firaxis have managed to remove the text for that LOC.

**Comment by JHCD** [comment]
No, there is a short word in the localisation:

````
<Replace Tag="LOC_HUD_REPORTS_BONUSES" Language="de_DE">
  <Text>{1: plural 1?Bonus; 2?Bonusse; other?Bonusse;}</Text>
</Replace>
````

There is a	linguistic differentiation "singular/plural" in the string.
So I think the string isn't called correctly.

**Comment by SpaceOgre** [comment]
That is probably the reason. The string is called just as it is in Vanilla, so it is an oversight by Firaxis. It is just added with `String="LOC_HUD_REPORTS_BONUSES"` on the xml element, I think the text needs to be fetched using `Locale.Lookup()`.

**Comment by ricanuck** [comment]
It's not the size, it's not Locale.Lookup...
Oh, Germans...  ;)

where is the style defined? It might be that.

**Comment by ricanuck** [comment]
OK, got it... it's the stupid pluralization of the string... I replaced the string for a single word (all we need, you know?) and it works fine. I will assume that the gerries (I love you) are the only ones with this problem and update the urs txt file, feel free to thinker with more languages if you want.

**Comment by JHCD** [comment]
That doesn't work. Civ skipped this entry as duplicated key.
Otherwise you would kill the correct single use on other UI elements.

**Comment by ricanuck** [comment]
It worked fine on my setup.

**Comment by JHCD** [comment]
I will play some turn with it...
Can't believe, that it is isolated for the mod only.

**Comment by JHCD** [comment]
Very funny... the issue is already in the original game...
Never missed that label ;)

**Comment by ricanuck** [comment]
Surpriiiisee!!!

Firaxis. The amount of bugs they introduced with this new "patch" is appalling... I know they have fallen low since the Soren times, but this low...?

**Comment by ricanuck** [comment]
Only option then is to transform the loc into a custom one, in honor of our Deutsches Volke... will do.

**Comment by JHCD** [comment]
In this case yes, but there a many of this plurals constructs in different language files.
So I think there must be a solution and they have only forgotten it in this xml.

**Comment by ricanuck** [comment]
Done. You can merge at will now.
