### ISSUE TITLE
it crash every time i try to change the setting. help plz

### ISSUE THREAD

**Issue by kuroiyukihime96** [CQUI-Org/cqui#476]
when im in game and i try to change the setting cause i dont want the production queue, it keep crashing and i cant do anything about it or when i want to use wasd but it keep crashing.

sorry for bad english.

**Comment by chaorace** [comment]
Are you using any other mods?

**Comment by kuroiyukihime96** [comment]
ok, i finally found out the problem after two hour. i think the problem is that it crash when i use the map inland sea. i try default map which is continents and it work but not inland sea

**Comment by kuroiyukihime96** [comment]
and also the original quick ui does not work as well. when i try to download it and add it to mod and dlc it does not show up in my civ6.

**Comment by chaorace** [comment]
The original QUI hasn't been updated since October and there's likely no chance whatsoever that it would work with the current game version. Just to confirm, you have no other mods beside CQUI installed, correct?

**Comment by kuroiyukihime96** [comment]
i use improved water yield and low warmonger but i also try without it and it still crash. i even try only using chaos quick ui for all map and only inland sea is the one that crash

**Comment by chaorace** [comment]
I've been hearing about crashing on the inland sea map type quite a bit recently, but have been unable to reproduce the issue, it would be very helpful if you could provide a savefile that consistently crashes for us to investigate

**Comment by kuroiyukihime96** [comment]
sure but it basically a default game with only the map type change to inland sea at turn 1

**Comment by kuroiyukihime96** [comment]
how do i give u my savefile?

**Comment by chaorace** [comment]
It's under "Documents\My Games"

**Comment by kuroiyukihime96** [comment]
it say we don't support that file type.

**Comment by brianschamel** [comment]
That's if you're trying to open the file.  All you need is to open the folder with the save file, click once on the save, and copy it (ctrl+c) into the text box on here.

**Comment by chaorace** [comment]
Right, well this topic is staling and I personally don't see any added value in keeping it open any longer
