### ISSUE TITLE
 A resource bundle lookup returned a fallback result

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#477]
Every time a start a game with CQUI enabled, this Warning is logged in _Localization.log_:

> Warning: ICU: A resource bundle lookup returned a fallback result (not an error)

Only CQUI is enabled and if CQUI isn't enabled there is no Warning.
Has anybody an idea? I can't figure out where it comes from.

**Comment by chaorace** [comment]
Probably has to do with the placeholder LOC file for IDS not actually being formatted correctly

**Comment by JHCD** [comment]
I changed it to a correct one...

**Comment by chaorace** [comment]
I don't really know what do with this warning, I think I'll just close this issue since it's not really leading anywhere
