### ISSUE TITLE
ProductionPanel: update to Spring patch with fixed "last production"

### ISSUE THREAD

**Issue by ricanuck** [CQUI-Org/cqui#481]
Now that Firaxis has finally solved the "last production bug", we should get rid of the CQUI code that compensated for that bug. As of now it is still working, but I found it not reliable, not always displaying the true last produced item.

I wanted to start on this, but I am not clear what part of the code is responsible for compensating the old, now fixed, bug in vanilla.

**Comment by JHCD** [comment]
Thats one of the problems of the productionpanel.lua... to komplex...
When going back to original code could reduce some parts, that would be nice...

**Comment by chaorace** [comment]
I believe just [these changes](https://github.com/CQUI-Org/cqui/commit/7de1fc8610f5ad87e1595b961e95498d1cdb84e0#diff-0aa3aaa2477170a97d59cce3324b2400) need to be reverted

**Comment by ricanuck** [comment]
nice, I had that impression, but wasn’t sure... will try and do it.

**Comment by bolbass** [comment]
Spring patch gives us more information when open production panel after an item completed. It also shows icons and total amount of hammers (gears) that we have. It is also color coded. So we need to revert some more changes. But I can't find what else to revert.
