### ISSUE TITLE
LaunchBar Improvements from HellBlazer's NQ Enhanced User Interface

### ISSUE THREAD

**Issue by SpaceOgre** [CQUI-Org/cqui#485]
Watched HallBlazer's stream tonight as he was adding stuff to his NQ Enhanced User Interface, and think we could incorporate some of the things he have done to the launch bar. Mostly I'm thinking about moving the Reports button there, but also when the world tracker is hidden show the tech/civ currently researching with timer circle.

![image](https://cloud.githubusercontent.com/assets/381657/24820557/fbe48664-1be9-11e7-9837-c61c572cc601.png)

What do you think?

**Comment by chaorace** [comment]
Agreed!

**Comment by JHCD** [comment]
I played some rounds with this branch from PR #487...
After ending a turn, it doesn't work anymore. I have to toggle the switch to activate it again...

![20170410223658_1](https://cloud.githubusercontent.com/assets/12496340/24881678/e548f852-1e3e-11e7-8239-14991f62594c.jpg)
