### ISSUE TITLE
ReportScreen - Units: Null-Exception

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#491]
With the newest CQUI master (2017-04-10) I get the following Exception:

''''
 Runtime Error: C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Integrations\URS\ReportScreen.lua:1685: attempt to index a nil value
stack traceback:
	C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Integrations\URS\ReportScreen.lua:1685: in function 'sort_units'
	C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Integrations\URS\ReportScreen.lua:2145: in function '(anonymous)'
''''

Not sure, if there is a dependency to #490

**Comment by ricanuck** [comment]
Does it crash the report screen?

**Comment by JHCD** [comment]
No, but I don't know if something is missing.
Only this Excpetion when I open the Report - mostly, not every time

**Comment by ricanuck** [comment]
Strange, never seen this before, but didn't try lately (Stellaris' fault..)... looking at the code, there is nothing new there, has not been changed in a long while, same for the other exception you are reporting... did you verify integrity via Steam?

**Comment by JHCD** [comment]
Yes, just now, no errors...

My savegame:
[FRIEDRICH BARBAROSSA 2 - RepScr.zip](https://github.com/CQUI-Org/cqui/files/910919/FRIEDRICH.BARBAROSSA.2.-.RepScr.zip)

**Comment by chaorace** [comment]
The game will often get a little exception-happy if you hotload often enough in a single session. I'm loading the save now to see if I can replicate, but that's my first hunch

**Comment by chaorace** [comment]
I was unable to replicate this issue

**Comment by ricanuck** [comment]
Same here, not able to replicate.
