### ISSUE TITLE
Resource icons are displayed incorrectly

### ISSUE THREAD

**Issue by PDMG** [CQUI-Org/cqui#499]
If I enable "Show Resource Icons" option in "Map Options", the icons are incorrectly displayed.
See image here: http://imgur.com/a/DjaEg

Game Resolution is set to 1600x900 as I am playing it in my laptop.
CQUI v0.6

**Comment by SpaceOgre** [comment]
v0.6 is not working with the last couple of patches, as stated on the release page:

> As of the fall patch, v0.6 is incompatible with the latest Civ release from the Winter Patch 2016. Worry not! You can still enjoy CQUI with the latest civ release using the nightly

**Comment by chaorace** [comment]
See issue #180 #184 #192 #267 and #268 for further information concerning your issue
