### ISSUE TITLE
City states overview panel text issue

### ISSUE THREAD

**Issue by HicPuer** [CQUI-Org/cqui#506]
City states overview panel > 
(Long) leader name overlaps influence number: 
![image](https://cloud.githubusercontent.com/assets/27763070/25316889/2f246438-2877-11e7-986d-bb46b5d68092.png)

Tested with 1440p and 1080p, seems that resolution do not affect this issue.

**Comment by SpaceOgre** [comment]
I think we maybe should truncate the name to a certain length and add ... and a tooltip with the whole name. A short name should most of the time be enough. 

It also seems like the background and the star for Suzerain are not matched.
