### ISSUE TITLE
Astog's Better Espionage Screen

### ISSUE THREAD

**Issue by SpaceOgre** [CQUI-Org/cqui#508]
Been playing around a bit with Astog's Better Espionage Screen and think it would fit great for CQUI.

**Comment by chaorace** [comment]
We already have permission to add it, buy we'll need to get a LOC pass done first before we actually add it to CQUI

**Comment by ricanuck** [comment]
I'm on it.

**Comment by ricanuck** [comment]
Done. Working fine on my side.
