### ISSUE TITLE
Perfomance issue during government/polices change (and trade screen)

### ISSUE THREAD

**Issue by HicPuer** [CQUI-Org/cqui#509]
There is temporary freeze every time I change government/polices. The freeze/delay is about few seconds and after this banners/numbers on top panel are updated (I can investigate it more, if this will be helpful for debugging). The freeze is longer in later eras.

I have i5-2500k 16GB SSD GTX1060 3G PC. Some another guy with laptop have 30+sec delay: https://forums.civfanatics.com/threads/cqui-a-ui-overhaul-now-out-on-steam-workshop.602771/page-29#post-14735019

Also there is sometimes long freeze and/or CTD when using trade screen.
Which Better Trade Screen version is included to CQUI? Is it latest beta: https://github.com/astog/BTS/releases/tag/v3.1-beta

**Comment by JHCD** [comment]
First question: Is it different without the Mod?
As far as I know Civ have to recalculate all values (gold, culture etc.) after changing the government/policies. Especially in later eras there are more objects you have to take into consideration.

Second: Astog himself integrated 3.1. here in January https://github.com/CQUI-Org/cqui/commit/ab9b3c18b9dd61ec3da238e87017a92d79d0fcdb

**Comment by HicPuer** [comment]
First "government/polices" issue: it's same without the mods. Seems that it core game issue. Sorry for not testing it at first place.

Second "BTS" issue: I compared the files with Winmerge and there were some differences...

**Comment by JHCD** [comment]
I have to take a look into it. I guess that are the last two original CIV patches...
