### ISSUE TITLE
CTD on Inland Sea Map (save file included)

### ISSUE THREAD

**Issue by SlicerNoSlicing** [CQUI-Org/cqui#512]
When trying to change CQUI settings on Turn 1 on an Inland Sea map, whichever CQUI setting I try and change first immediately leads to a CTD.  Happens w/ and w/o other mods installed. Since I've read you are aware of the issue but cannot reproduce, I've attached a Turn 1 save file with only CQUI. Hopefully this helps you find the problem. 

[TRAJAN 1 - INLAND SEA CQUI CRASH.zip](https://github.com/CQUI-Org/cqui/files/966321/TRAJAN.1.-.INLAND.SEA.CQUI.CRASH.zip)

**Comment by SBeckham** [comment]
I had maybe 7-10 crashes with inland sea map. I first didn't understand that the map was problem but the mod works great with all other map types. All the games I started inland sea crashed, T1 CTD.

**Comment by bolbass** [comment]
@chaorace I checked it and found that this issue don't appear if we remove function `GetMapInitData(MapSize)` from `InlandSea.lua`. What should we do with this?
