### ISSUE TITLE
Possible problem repairing walls

### ISSUE THREAD

**Issue by SpaceOgre** [CQUI-Org/cqui#513]
There might be a problem with PQ and repairing walls, as in they dissappear and you can build them again. 

This is mostly a reminder for my self to check it thoroughly when I get the time.

**Comment by JHCD** [comment]
I know that problem...
After exploring architecture (? - German: Bauwesen) it isn't possible to build / repair walls.

**Comment by chaorace** [comment]
This is because civil engineering gives a a flat defense bonus which effectively obsoletes walls entirely. It's not very well documented, but it's the same in the base game
