### ISSUE TITLE
IDS: traded items - rounds left

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#523]
It would be nice if the tooltip shows the left rounds for a traded ressource.

**Comment by ricanuck** [comment]
That's interesting. Will go for it.

**Comment by JHCD** [comment]
Yeah, that would be nice...
Sometimes the original leader comes back with the same offer. 
So it would be essential if the old trade will end next turn or 15 rounds later

**Comment by ricanuck** [comment]
Done!

**Comment by JHCD** [comment]
Great, thanks!!
