### ISSUE TITLE
City Production Window bug

### ISSUE THREAD

**Issue by ZZFrag** [CQUI-Org/cqui#533]
When you load a save (Only tested: Multiplayer Game) I find that the city production windows either get stuck on screen or refuse to open. While I have had this sporadically happen on a game that wasn't loaded from a save, It generally gets much worse on saved games.

An example of this effect is when you want to buy a unit or change production of a city, you will not be able to open the city production screen to do so until the current queue empties, and you are prompted to select the next unit/etc that you wish to produce.

Sorry for the poor description, If you have any further questions, just let me know.

Issue is similar to this:
https://github.com/CQUI-Org/cqui/issues/519

**Comment by ZZFrag** [comment]
This is my Lua.log file if that helps.
https://pastebin.com/tRAVFbVC

**Comment by Kilo59** [comment]
This happened to me very early on in a Single player game about a week ago. It eventually resolved itself but I don't why.

**Comment by chaorace** [comment]
This is indeed very similar to #519, so I'm labeling this issue as a duplicate and closing it now
