### ISSUE TITLE
Slow down later in game

### ISSUE THREAD

**Issue by codymj** [CQUI-Org/cqui#539]
Hello, I love this mod. However, by mid game, production screen rendering is very, very slow. Not sure what the reason could be. Disabling mod makes the production screen render quickly again, but I'd much rather have the mod active.

**Comment by bolbass** [comment]
Hi. Can you upload a savefile?

**Comment by codymj** [comment]
Yes. I will work through a new game to create one soon.

**Comment by codymj** [comment]
It seems if I restart the game, the delay goes away. So, I will close this.

**Comment by chaorace** [comment]
For future searchers, please see #537 for progress towards improving the performance of long gameplay sessions
