### ISSUE TITLE
New contributor ramp-up pitfall

### ISSUE THREAD

**Issue by zlychaos** [CQUI-Org/cqui#542]
Hi,

This seems to be a fun project and I am interested in contributing. But the ramp-up was not so smooth.

I was trying some stuff but I could not get my game to use the downloaded version by copying the repo folder to DLC/. I am using Windows 10 and Steam. Not sure if I have to unsubscribe CQUI in Steam.

Gitter seems to have been quiet for some time.  What is the best place for quick questions? 

Thanks.

**Comment by JHCD** [comment]
Using both (Steam and lokal) CQUI versions is a little bit complicated.
I would prefer to unsubscribe the Steam version and install a git-version in civ/mods.

After that is running you can start with your changes.

**Comment by chaorace** [comment]
I too use git instead of the workshop version

As for quick questions, shoot me an email chaorace@gmail.com
I'm looking into maybe moving discussion over to a discord channel to better interact with the community anyways

**Comment by zlychaos** [comment]
Thanks JHCD and Chris. Unsubstribing steam workshop fixed the issue.
