### ISSUE TITLE
Add option to borrow/lend gold in deal screen

### ISSUE THREAD

**Issue by freongrr** [CQUI-Org/cqui#543]
When I'm in a pinch and need gold right now, I often exchange a lot of gold now against some gold every turn. Basically I'm borrowing money for my Civ from an other Civ. It's pure roleplay, but it could be turned into a feature pretty easily.

In the deal screen, have a Borrow and Lend gold options that ask for a sum and a percentage. I'm not sure what's the "interest" margin. Maybe the percentage can't really be changed? For fun, it could show a rating to let you know how reliable your Civ appears (AAA, BB, C, etc).

I suspect this is something the Improved Deal Screen mod would have to do, but I could not find their tracker.

**Comment by chaorace** [comment]
This falls waaay outside the purview of CQUI
