### ISSUE TITLE
Patronage not showing up

### ISSUE THREAD

**Issue by Entropy0** [CQUI-Org/cqui#544]
There are no buttons/ amounts displayed beneath the "Or recruit with Patronage:" line in the Great People tab. Not that I'd actually _use_ them, but I'd still like to have the option...

**Comment by Entropy0** [comment]
Oddly enough, the buttons showed up after some time. Probably still worth looking into.

**Comment by chaorace** [comment]
Sounds like a mod conflict, what other mods do you play with?

**Comment by Entropy0** [comment]
None other than CQUI.

I've played around a bit and it seems that this always happens on the first turn after opening a game (whether starting a new game or loading an old one).

**Comment by bolbass** [comment]
@Entropy0 can you show a screenshot of this issue?

**Comment by Entropy0** [comment]
![20170622211732_1](https://user-images.githubusercontent.com/11321572/27451875-df2b077c-5790-11e7-9475-af556e6fb97d.jpg)
This happens every time I create or load a game, but fixes itself once I play a few turns (most of the time, one is enough)

**Comment by bolbass** [comment]
@Entropy0, these buttons should appear right after you found your first city. Try it and if it's ok close the issue.

**Comment by chaorace** [comment]
Closing due to lack of response, will reopen if @Entropy0 provides further feedback
