### ISSUE TITLE
pop-ups menu

### ISSUE THREAD

**Issue by mrhammy82** [CQUI-Org/cqui#554]
I do not appear to have the pop-ups menu in my settings menu.

I want the tech and civics pop-ups when they complete and I cannot seem to find a way to turn them back on.

I fully appreciate that I am doing something wrong but am at a loss.

Can someone please point me in the right direction.

Thank you in advance.

M

**Comment by bolbass** [comment]
Update CQUI to the latest nightly. You can download it from [here](https://github.com/CQUI-Org/cqui/archive/master.zip). Then you can find these settings in CQUI settings menu: Popups >> Tech/Civic popup visual.
