### ISSUE TITLE
4 resource icons showing

### ISSUE THREAD

**Issue by mrhammy82** [CQUI-Org/cqui#555]
All resources are showing 4 different icons.  as an example, for fish there is a fish icon and cotton, gems and rice icon.

**Comment by Kobanister** [comment]
+1 Same issue.

**Comment by bolbass** [comment]
Update CQUI to the latest nightly. Download it from [here](https://github.com/CQUI-Org/cqui/archive/master.zip)
See issues #180 #184 #192 #267 #268 #499 for further information concerning your issue.
