### ISSUE TITLE
UI elements don't update

### ISSUE THREAD

**Issue by beshmudi** [CQUI-Org/cqui#561]
both civics/techs appear with a timer of 33 turns left and are unusable, however starting a research through them starts the research but doesn't show it.
the button to open the full trees do nothing.
the turn counter doesn't increment either.
the government and great people tabs don't open either.

![image](https://user-images.githubusercontent.com/20864579/27260093-3826b6ec-541b-11e7-9044-5a5ee1a12a55.png)

**Comment by bolbass** [comment]
disable mods that conflict with CQUI
