### ISSUE TITLE
resources display error x4

### ISSUE THREAD

**Issue by karitr1** [CQUI-Org/cqui#567]
after installing CQUI i've got resources view error x4. tried different CQUI versions. my game version is 1.0.0.129
see snapshot please
![civ6](https://user-images.githubusercontent.com/29690434/27516927-c1b19e44-59cb-11e7-9c45-9ae837694c25.jpg)

**Comment by Meller008** [comment]
+1

**Comment by karitr1** [comment]
this is a duplicate topic. i'm sorry guys. please close this.

**Comment by bolbass** [comment]
Update CQUI to the latest nightly. You can download it from [here](https://github.com/CQUI-Org/cqui/archive/master.zip). If you're still having issues, consider checking if your game install is up to date or if another mod you've installed is introducing any incompatibilities.
See issues #180 #184 #192 #267 #268 #499 #555 for further information concerning your issue.
And next time please use search on issue tracker before opening new issues.
