### ISSUE TITLE
Multiple resource icons showing up for one resource tile.

### ISSUE THREAD

**Issue by markerobinson** [CQUI-Org/cqui#574]
It appears the resource tile has the correct icon in the upper left, but you can see three or four icons per tile.

Let me know if I can provide additional information.

![image](https://user-images.githubusercontent.com/14986706/27848276-c48fb4d2-60f8-11e7-8bd1-1f95a5dc7784.png)

**Comment by bolbass** [comment]
Update CQUI to the latest nightly. You can download it from [here](https://github.com/CQUI-Org/cqui/archive/master.zip). If you're still having issues, consider checking if your game install is up to date or if another mod you've installed is introducing any incompatibilities.
See issues #180 #184 #192 #267 #268 #499 #555 #567 for further information concerning your issue.
And next time please use search on issue tracker before opening new issues.

**Comment by markerobinson** [comment]
Understood. I was looking for open issues, not closed ones.  Thanks for the prompt reply.
