### ISSUE TITLE
Redesign the Great People dialog

### ISSUE THREAD

**Issue by jacks0nX** [CQUI-Org/cqui#58]
@zyxpsilon Design:
![](https://cloud.githubusercontent.com/assets/23318465/20074787/b7a44d7e-a4ff-11e6-950f-589375cbc4c3.png)

See #40:
"Yep.. maintaining the terms "PROGRESS" and "With Patronage" above the costs duo would be preferable too i guess.
The trick i gather will be to calibrate the Modal dispatch and possibly create a new DDS image (BLP packaged) to fit the narrower framing -- and for that, we'd need the SDK for sure. Unless you'd have some other magic indirect solution.
Don't forget the big round GP faces can also be discarded or re-sized if need be. IIRC, the glower effects (top banners & GP circles) are just thrown individually as well.
Good luck! :)"

**Comment by chaorace** [comment]
Fixing up the GP view relies on replacing some key textures like the background boxes, which are actually baked in. This is an issue that can only be tackled properly with the SDK tools

**Comment by zyxpsilon** [comment]
If only that SDK would just come our ways -- soooooooonnnnn! ;(

**Comment by vttale** [comment]
Maybe this CR is the wrong place to ask, but could the progress bars be modified to include how many turns to fill?  You can currently figure this out with mouseover and math, but that's annoying for something that should be readily visible.

**Comment by chaorace** [comment]
The GP view has been iterated upon considerably since the creation of this ticket. I feel it's no longer a valid criticism to say it needs redesigning and am closing this issue

**Comment by JHCD** [comment]
Reducing the width could fit all GPs into one screen...

![20170319103113_1](https://cloud.githubusercontent.com/assets/12496340/24079730/44eec104-0c8f-11e7-9146-8aff54cb1e9e.jpg)
