### ISSUE TITLE
Research and culture tree issues

### ISSUE THREAD

**Issue by IceDragon22** [CQUI-Org/cqui#580]
Starting a new game with the latest version, I am not able to open the Science or Culture trees and the science and culture tabs always show as blank with 33 turns remaining, even if I am able to pick a tech or culture to study.  Disabling CQUI and starting a new game does not have this problem, it only shows when I start a game with CQUI enabled.

**Comment by bolbass** [comment]
See #561 and use search on issue tracker next time please before opening a new issue.

**Comment by chaorace** [comment]
You mention you're using the latest version, which makes this distinct from the prior mentioned issues. Just to be sure, what's your game version? (you can find this info from the pause menu)

**Comment by chaorace** [comment]
@IceDragon22 In order to address your issue, I need a response
