### ISSUE TITLE
Unable to build districts

### ISSUE THREAD

**Issue by Smiggy1968** [CQUI-Org/cqui#584]
HI
I am about 150 turns in.  I can't build new districts in any  of my 5 citiies.   In the production screen, the relevant icons are there but If i click on one the screen tilts but no tiles are highlighted and available for placing districts.  Apologies if this has been reported and resolved before. I did do a search of the discussions, forums, github etc but found nothing relevant.   
Regards

**Comment by chaorace** [comment]
Are you using any other mods?

**Comment by Smiggy1968** [comment]
Hi Chris
Yes, I've got Deliverator's Alternative Civilisation colors,  Toft's Policy Bonanza and Lozenged's Production Queue.  I've just tried disabling them all, leaving onlyCQUI enabled and the problem persists.
Thanks Martin


On Tuesday, July 18, 2017, 3:33:31 AM GMT+1, Chris <notifications@github.com> wrote:


Are you using any other mods?

**Comment by chaorace** [comment]
Disabling mods in the main menu does _not_ disable them in existing saves. You can confirm this by viewing the mod from the main menu load screen, there is a mod list there which shows the "locked in" mods. CQUI includes an enhanced version of the production queue mod and is incompatible with Lozenged's original version. Running both mods at once is known to cause your issue
