### ISSUE TITLE
Skip song function

### ISSUE THREAD

**Issue by cpinter** [CQUI-Org/cqui#592]
Hotkey or button to skip to next song.

If someone could point me where to start looking that would be great!

**Comment by chaorace** [comment]
I believe this is already a mod. I have no interest with merging it into CQUI, since it stands to be quite useless to many people

**Comment by cpinter** [comment]
If it's a mod it's fine, I'll try to find it.

However the statement "quite useless to many people" is your own subjective opinion, and it's a bit of a stretch!
