### ISSUE TITLE
Feature: Alternate Citizen Management Lens

### ISSUE THREAD

**Issue by astog** [CQUI-Org/cqui#598]
Hey @chaorace . I implemented a new type of lens called _Area_, where any plots colored the same will be grouped together. It only works on owned tiles but one way we can use them is to show the citizen management area. Below are the results:

_This will be shown when hovering on the city banner_
_Green - Locked Tiles_
_Yellow (changing this to orange) - Unlocked Tiles_
![Imgur](http://i.imgur.com/EyJ2hqR.jpg)

_In citizen management screen_
![Imgur](http://i.imgur.com/YRXD5dp.jpg)

Since this is the same as in CQUI showing citizen icons when hovering, do you want me to replace it, or add it as an extra option (retaining the old code)?

**Comment by astog** [comment]
OK, so editing the settings screen was really easy. So I just added extra options there, and retained all the old code. But do you want the previous implementation as default, or this one?

**Comment by chaorace** [comment]
Oh man that is one sexy overlay! Considering how relatively clumsy the old worked tile implementation was, along with how generally displeasing I'm told it looked, I think we can scrap the old implementation for this one

**Comment by astog** [comment]
This feature is now merged. So I am closing this issue.
