### ISSUE TITLE
Buttons for cycling cities in cityview

### ISSUE THREAD

**Issue by chaorace** [CQUI-Org/cqui#6]
Big buttons on either side of the citybanner that cycle cities, appears only in the CITY_MANAGEMENT interface mode

**Comment by olegbl** [comment]
Is this different from the arrows next to the name?
![image](https://cloud.githubusercontent.com/assets/516977/19833043/36eef1b0-9de9-11e6-8df8-278f9b5330b4.png)

**Comment by chaorace** [comment]
No, but like the XP bar it's so small and in such a cluttered spot that
people can't find it! There's also the case to be made for putting the
navigation buttons closest to where the user's cursor spends the majority
of its time

**Comment by chaorace** [comment]
Sacking this proposed change since it would probably clutter the city banner too much and be prone to misclicks
