### ISSUE TITLE
Notification icons (bottom right) not working, white path always shown

### ISSUE THREAD

**Issue by ChristophRettinger** [CQUI-Org/cqui#606]
I just tried this mod for the first time - it looks awsome, but I have a show stopper problem:

Those notification icons in the lower right section (showing completed tasks, huts, wars, etc) has only a generic icon and no tooltip and it cannot be clicked on. 

![qcui-notificationbug](https://user-images.githubusercontent.com/19951711/28921577-c24158d2-7856-11e7-84e5-e113fe2699b7.png)

Also white line is always shown for my unit even if it has no given way to travel. Also my settler had it right from the beginning of the game.

I tried the subscription and a manual installation (both 2 times), but to no avail.

Hope this is a bug easily fixed :)

regards

**Comment by JHCD** [comment]
Hi Christoph,

CQUI isn't compatible yet with the new Summer 2017 patch.
Progress see #591.

You could download an test the [Summer-2017 branch](https://github.com/CQUI-Org/cqui/tree/summer-2017). It works, but with many issues too.

Regards,
Jens

**Comment by ChristophRettinger** [comment]
ok, thanks. I was looking if someone had this issue, but did not know how to phrase it.

keep up the great work

**Comment by madjestic** [comment]
The linked discussion (JHCD closed this on Aug 3) is closed, what is the status of this?

**Comment by chaorace** [comment]
@madjestic [This repo is closed](https://github.com/CQUI-Org/cqui/commit/c96971bb65b0cd4857a50e81d8130164b7b4ea72), soon to be archived. I respectfully ask that you consult the README to learn about where you can find a supported version of this mod.

**Comment by madjestic** [comment]
I am sorry for being ignorant.  I got the mod version from the cqui-summer-2017 branch running.
