### ISSUE TITLE
Can't build wonders

### ISSUE THREAD

**Issue by warwolf666** [CQUI-Org/cqui#608]
Hello,
I have CQUI installed from the Steam Workshop, and the Civ VI default version with the default DLCs, and just the CQUI mod installed. I'm running the DX12 version on Win 10.

The problem is that it doesn't let me build Wonders. The only available tiles have something already built on them, so I'm assuming that's the issue. Clicking on the green tile doesn't do anything :(

I'm attaching the [Save Game](https://github.com/CQUI-Org/cqui/files/1202948/VICTORIA.34.2680.BC.zip) with the issue. To repro, just go to London Production and try to build the Forbidden City Wonder on the only available tile:
![image](https://user-images.githubusercontent.com/778397/29001549-1b9d476a-7a96-11e7-8707-818975a05398.png)

Please let me know if I can provide any more info.

Thanks !

**Comment by BlackSmokeDMax** [comment]
Not compatible with summer patch yet.

**Comment by JCron245** [comment]
@BlackSmokeDMax 
As Black Smoke has said the latest patch for Civ 6 (Summer Patch 2017) has broke compatibility with this mod. The people in charge of this mod are working hard on making CQUI compatible with the new patch, you can check out the other open issues here and there is thread for Summer Patch 2017 problems 

[Summer Patch 2017 - CQUI Open Issue](https://github.com/CQUI-Org/cqui/issues/591)

**Comment by warwolf666** [comment]
Oh, I see. I haven't noticed the game updated :(

Thank you very much !
