### ISSUE TITLE
Can't open Policies Page; Can't Advance past Code of Laws Civic

### ISSUE THREAD

**Issue by Solrac1980** [CQUI-Org/cqui#610]
I'm having a few issues with CQUI, I can't open policies page, and can't advance past Code of Laws civic. Also, my notifications on the right side of the screen are replaced by blue exclamation point circles, and finally, all of the tile yields on my screen are showing, all the time, that's annoying and takes away from the game's realism. I just want to know, are there maybe compatibility issues with other mods I've installed, am I missing some settings, or am I just plain retarded? Does someone have an answer for this?

**Comment by JHCD** [comment]
Hi,

CQUI isn't compatible yet with the new Summer 2017 patch.
Progress see #591.

You could download an test the Summer-2017 branch.
In #591 is a workaround to use CQUI with the Summer 2017 patch too.

Regards,
Jens
