### ISSUE TITLE
Feature Request: Changes for barbarian and scout lenses

### ISSUE THREAD

**Issue by JustNilt** [CQUI-Org/cqui#624]
I'd like to be able to do 2 things:

1. Have the barbarian lens auto-apply for military units.
2. Add barbarian encampments to the scout lens, probably using the same color as the standalone lens.

I've been tinkering and trying to figure out how to do this myself but being a newbie to Civ modding, it's a bit more complex than I am capable of doing.  My reasons for this are when playing as Sumeria, it's nice to be able to use scouts to clear empty encampments, but seeking them out is rather tedious as it is.  Being able to hunt barbarians with any military unit would also be very nice.

**Comment by JustNilt** [comment]
I know it's bad form to reply to myself but I wanted to be certain I get this noted and, for some reason, editing isn't working.  Weird.

I've been pokling around and figured out how to accomplish #1 above, having the Barbarian Lense auto apply for military units.  I even got it working for the MOAR Units mod, though I'm uncertain if it would be appropriate to include those in an update.  Now I just need to figure out how to get those changes sent to someone who can test them, etc, and then merge them in.  As best I can tell, I need to fork the project and put my own changes in.  Will work on that; this is more a note to myself at this stage unless since I am about done for the day unless someone has a tutorial all set for that.

**Comment by ProustIdee** [comment]
Hi @JustNilt, development is happening on this repository now: https://github.com/Azurency/CQUI_Community-Edition

**Comment by JustNilt** [comment]
Thanks, @Proustldee. I discovered that yesterday or the day before. Thanks, though! I'd been wondering why it was so quiet. Ha!
