### ISSUE TITLE
Show "the offender" causing AI negative diplomatic feedback

### ISSUE THREAD

**Issue by layzsmurf** [CQUI-Org/cqui#65]
As the game currently stands, I have a hard time to understand why I do fail certain diplomatic promises:

* Army at the border - there are games where I am 100% certain I did move them away
* Do not convert my cities

It would be great if the game could hint which city or unit was affected.

I also believe there is a bug in the convert detection.

I had Taoism and I "bombed" a Roman city - say Antium, and Caesar asked me to stop converting his cities (which means he had a religion on his own), but was already converted by Ghandi to Hinduism.

So I left the city alone (and did not engage in any religious combat) after some 10 turns I failed my promise, as the city flipped back from Taosim to Hinduism - the majority religion in the region. I believe the code just checks if the religion is the founding religion or not and this decides the success or fail.

**Comment by chaorace** [comment]
This may not actually be possible, it depends on how transparent Firaxis made the AI. My guess is not very! Still, I'll investigate this in the future

**Comment by chaorace** [comment]
Closing this as a, most likely, impossible request
